title: Ines Šimičić Portfolio
author:
  name: Ines Šimičić
description: > # this means to ignore newlines
  A collection of various little gems I've done outside of workplace, or during the interview processes. Some might be even laughing stock today, but it's good reminder of the whole journey :)

show_excerpts: false # set to true to show excerpts on the homepage

permalink: /:categories/:year/:month/:title:output_ext

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Ines Šimičić"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -

minima:
  # Minima date format
  # refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
  date_format: "%b %Y"

  # generate social links in footer
  social_links:
    github: inesucrvenom
    linkedin: inessimicic

  skin:
    classic

# Build settings
theme: minima

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2

# Jekyll-paginate-v2 configuration
# See https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md
pagination:
  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 10
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page:num/' # Pages are index.html inside this folder (default)
  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'
  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true
